excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://remcoder.github.io
title: Remcoder's blog
tagline: Real stuff for abstract people
description: My awesome new site
paginate: 5